/// Flutter icons Hackbiz
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hackbiz
///      fonts:
///       - asset: fonts/Hackbiz.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Hackbiz {
  Hackbiz._();

  static const _kFontFam = 'Hackbiz';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping_fast = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_rightcircle = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag2_1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_square = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
